server:
  port: 80

spring:
  config:
    import:
      - classpath:/app/cors/cors.yml
#      - classpath:/app/jwt/jwt.yml
#      - classpath:/app/password/password-encoder.yml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${db.url:jdbc:mysql://localhost:3307/demo_signup?allowPublicKeyRetrieval=true}
    username: ${db.username:root}
    password: ${db.password:root}
    hikari:
      connectionTimeout: 10000
      idleTimeout: 600000
      maximum-pool-size: 300
      minimum-idle: 5
      maxLifetime: 10000
      leak-detection-threshold: 2000
  jpa:
    hibernate:
      ddl-auto: none # validate, ... <- Flyway: JPA DDL-AUTO: none or validate
    properties:
      hibernate:
        format-sql: false
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:/db/migration # Default
